server:
  port: 8000

spring:
  application:
    name: currency-exchange-service
  jpa:
    show-sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  security:
    user:
      name: user
      password: password

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /manage

eureka:
  instance:
    hostname: discovery-server
    instance-id: ${spring.application.name}
  client:
    serviceUrl:
#      default-zone: http://localhost:8761/eureka    ## local configuration
      defaultZone: http://discovery-server:8761/eureka/
    registerWithEureka: true