spring:
  security:
    user:
      name: user
      password: password
  application:
    name: currency-conversion-service
server:
  port: 8100

management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: '*'

eureka:
  instance:
    hostname: discovery-server
    instance-id: ${spring.application.name}
  client:
    serviceUrl:
      default-zone: http://localhost:8761/eureka/
    registerWithEureka: true

feign:
  client:
    config:
      default:
        connectTimeout: 50000
        readTimeout: 50000