spring:
  security:
    user:
      name: user
      password: password
server:
  port: 8100

management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: '*'

feign:
  client:
    config:
      default:
        connectTimeout: 50000
        readTimeout: 50000